### ISSUE TITLE
perl

### ISSUE THREAD

**Issue by petrivanov1** [lemurio/ispmanager4-php-version#1]
Здравствуйте, а Вы не сталкивались с ошибкой:
<pre>Can't locate object method &quot;read&quot; via package &quot;XML::LibXML::Document&quot; at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML.pm line 882. at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML/SAX.pm line 99.
 at /usr/local/share/perl/5.24.1/XML/Simple.pm line 393.
XML::Simple called at ./phpver.pl line 157.
</pre>
?

**Comment by lemurio** [comment]
Здравствуйте. Нет, не сталкивался. Вероятно пустой/не правильный вывод от ISPmanager.
